// Generated by CoffeeScript 1.7.1
(function() {
  var filenameMediaQuery, should;

  filenameMediaQuery = require('../');

  should = require('should');

  describe('gulp-filename-media-query', function() {
    return describe('sotit()', function() {
      return it('should do stuff', function() {
        return true.should.be.ok;
      });
    });
  });

}).call(this);
