// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var buffer, filenameMediaQuery, path, through, util;

  buffer = require('buffer').Buffer;

  path = require('path');

  through = require('through2');

  util = require('gulp-util');

  filenameMediaQuery = function() {
    var collect, extensions, files, process, regex, units;
    units = ['ch', 'cm', 'em', 'ex', 'in', 'mm', 'pc', 'pt', 'px', 'rem', 'vh', 'vw'];
    extensions = ['css', 'sass', 'scss'];
    regex = {
      file: new RegExp("/(([<>]\\d+(" + (units.join('|')) + "))|(=\\d+(" + (units.join('|')) + ")-\\d+(" + (units.join('|')) + ")))\\.(" + (extensions.join('|')) + ")$"),
      value: new RegExp("[<>=](.+)\\.(" + (extensions.join('|')) + ")")
    };
    files = {};
    collect = function(file, _, callback) {
      var name;
      if (regex.file.test(file.path)) {
        name = path.basename(file.path);
        if (!files.hasOwnProperty(name)) {
          files[name] = [];
        }
        files[name].push(file);
      } else {
        this.push(file);
      }
      return callback();
    };
    process = function(callback) {
      var dimension, group, name, query, sign, suffix;
      for (name in files) {
        group = files[name];
        query = '@media screen and ';
        sign = name[0];
        suffix = path.extname(name).substring(1);
        dimension = name.replace(regex.value, '$1');
        switch (sign) {
          case '<':
            query += "( max-width: " + dimension + " )";
            break;
          case '>':
            query += "( min-width: " + dimension + " )";
            break;
          case '=':
            dimension = dimension.split('-');
            query += "( min-width: " + dimension[0] + " ) and ( max-width: " + dimension[1] + " )";
            break;
          default:
            throw new util.PluginError('gulp-filename-media-query', 'Illegal file extension');
        }
        if (suffix === 'sass') {
          query += '\n\t' + group.map(function(file) {
            return file.contents.toString().split('\n').join('\n\t');
          }).join('\n');
        } else {
          query += ' {\n';
          query += group.map(function(file) {
            return file.contents.toString();
          }).join('\n');
          query += '\n}';
        }
        this.push(new util.File({
          cwd: group[0].cwd,
          base: group[0].base,
          path: group[0].path,
          contents: new Buffer(query)
        }));
      }
      return callback();
    };
    return through.obj(collect, process);
  };

  module.exports = filenameMediaQuery;

}).call(this);
